### ISSUE TITLE
stringhe volanti

### ISSUE THREAD

**Issue by LuigiVessella** [LuigiVessella/hello_ncurses#1]

**Comment by LuigiVessella** [comment]
Prof perchè il programma non va? Non aspetta i secondi e le stampe tutte e 3 nonostante i refresh in mezzo.

**Comment by FabioZTessitore** [comment]
chi controlla quanto tempo deve passare tra una stampa e l'altra?

**Comment by LuigiVessella** [comment]
Tempo

**Comment by LuigiVessella** [comment]
nanosleep(&tempo

**Comment by FabioZTessitore** [comment]
nanosleep è la funzione, ma i dati stanno altrove, controlla invece di scrivere qui

**Comment by FabioZTessitore** [comment]
Hai capito cosa avevi sbagliato?

**Comment by LuigiVessella** [comment]
fatto

**Comment by LuigiVessella** [comment]
si...nsec avevo scritto sec
