### ISSUE TITLE
gitignore

### ISSUE THREAD

**Issue by FabioZTessitore** [LuigiVessella/hello_ncurses#2]
aggiusta

**Comment by LuigiVessella** [comment]
Fatto

**Comment by FabioZTessitore** [comment]
Aggiustare non significa solo aggiungere quello che manca

**Comment by LuigiVessella** [comment]
ah hello ci sta perchè si trova nella cartella sul mio pc..l'ho usato per esercitarmi con ncurses

**Comment by LuigiVessella** [comment]
Che cambia se ci sta o no

**Comment by FabioZTessitore** [comment]
Cambia perché se volessi aggiungere io il file hello.c non me lo caricherebbe. Se vuoi programmare devi fare le cose per bene

**Comment by LuigiVessella** [comment]
Ok, fatto.
